apiVersion: skaffold/v2beta23
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - context: .
    image: us-central1-docker.pkg.dev/tgg-sre-testing/tgg-skaffold-doodads/cdwebapp
deploy:
  helm:
    releases:
      - name: "cdwebapp-dev"
        chartPath: "../helm-cdwebapp"
        namespace: cdwebapp-sjahl
        createNamespace: true
        valuesFiles: 
          - "../helm-cdwebapp/values-dev.yaml"
        artifactOverrides:
          imageKey: us-central1-docker.pkg.dev/tgg-sre-testing/tgg-skaffold-doodads/cdwebapp

