name: Build and Release
on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Go Build"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - run: go build
        env:
          GOOS: linux
          GOARCH: amd64
      - uses: actions/upload-artifact@v2
        with:
          name: "build-output-${{ github.sha }}"
          path: ./cdwebapp
          retention-days: 2
  docker_release:
    runs-on: ubuntu-latest
    name: Release Docker Image
    needs: build
    outputs:
      imageTag: ${{ steps.slug.outputs.sha8 }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - uses: actions/download-artifact@v2
        name: "build-output-${{ github.sha }}"
      - name: move binary into cwd
        run: "mv build-output-${{ github.sha }}/cdwebapp ."
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build & Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: stephenjahl/cdwebapp:${{ steps.slug.outputs.sha8 }}

